# Generated by Django 2.0.7 on 2019-10-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.FileField(blank=True, default='default.png', upload_to=''),
        ),
    ]
